// <auto-generated />
using FrizerskiSalonBackend.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FrizerskiSalonBackend.Migrations
{
    [DbContext(typeof(FrizerskiSalonContext))]
    [Migration("20220708174050_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("FrizerskiSalonBackend.Models.Korisnik", b =>
                {
                    b.Property<int>("korisnikId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("korisnikId"), 1L, 1);

                    b.Property<string>("adresa")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ime")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("prezime")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("telefon")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("tip")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("korisnikId");

                    b.ToTable("Korisnik");
                });

            modelBuilder.Entity("FrizerskiSalonBackend.Models.Proizvod", b =>
                {
                    b.Property<int>("proizvodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("proizvodId"), 1L, 1);

                    b.Property<int>("cena")
                        .HasColumnType("int");

                    b.Property<string>("naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("opis")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("proizvodId");

                    b.ToTable("Proizvod");
                });

            modelBuilder.Entity("FrizerskiSalonBackend.Models.SlikaProizvoda", b =>
                {
                    b.Property<int>("slikaProizvodaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("slikaProizvodaId"), 1L, 1);

                    b.Property<int>("proizvod")
                        .HasColumnType("int");

                    b.Property<string>("putanja")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("slikaProizvodaId");

                    b.ToTable("SlikaProizvoda");
                });

            modelBuilder.Entity("FrizerskiSalonBackend.Models.SlikaUsluge", b =>
                {
                    b.Property<int>("slikaUslugeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("slikaUslugeId"), 1L, 1);

                    b.Property<string>("putanja")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("usluga")
                        .HasColumnType("int");

                    b.HasKey("slikaUslugeId");

                    b.ToTable("SlikaUsluge");
                });

            modelBuilder.Entity("FrizerskiSalonBackend.Models.Usluga", b =>
                {
                    b.Property<int>("UslugaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UslugaId"), 1L, 1);

                    b.Property<int>("Cena")
                        .HasColumnType("int");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UslugaId");

                    b.ToTable("Usluga");
                });
#pragma warning restore 612, 618
        }
    }
}
